---
title: "NullPointer Bros"
sidebar: false 
---

MUY660-İş Analitiği dersi takım sayfamıza hoş geldiniz.

Bu analitik çalışmalarımızı paylaşıyoruz.

Lütfen faaliyetlerimizi görmek için için bizi takipte kalın.

## Takım Üyeleri

1.  [Barış Doğan AVTAN](/takim/barisdoganavtan.qmd)

2.  [Uğur Topak](/takim/ugurtopak.qmd)

3.  [Mehmet Akın](/takim/mehmetakin.qmd)

## Proje Adı

MUY660-İş Analitiği iyileştirme çalışmaları (örnek)

## Proje Konusu

Örnek: Bu projede MUY660-İş Analitiği ders içeriğinin analitik yaklaşımlarla iyileştirilmesini hedefledik. Bu doğrultuda tüm üniversitelerdeki benzer derslerin verisini toplayarak bir veri seti oluşturduk Analiz için ........ yöntemleri kullanarak, ....... çalışmaları yaptık Sonuç olarak, MUY660-İş Analitiği dersinin dünyadaki tüm derslerden daha iyi olduğunu ve bu dersi aldığımız için çok mutlu olduğumuzu tespit ettik.

## Veri Seti Hakkında Özet Bilgi

-   **Veri Seti**: `mtcars` (Motor Trend Arabalar Veri Seti)

-   **Gözlem Sayısı**: 32 araç

-   **Özellikler**: Beygir gücü (`hp`), yakıt verimliliği (`mpg`), ağırlık (`wt`), silindir sayısı (`cyl`) gibi 11 sayısal özellik

-   **Kullanım Amaçları**:

    -   Fonksiyon yazarak özet istatistikler hesaplama

    -   `for` döngüsü ile kolonları analiz etme

    -   `apply()` fonksiyonu ile vektörel analiz

    -   Araç performansı görselleştirme (hp vs. mpg)

## Sonuçlar

1-**Beygir gücü ile yakıt verimliliği** ters orantılı: Güç arttıkça verim düşüyor.

`2-mpg` (yakıt verimliliği) ortalaması **20.1**, ama bazı araçlar 10’un altında. Demek ki 1970’ler çevreye pek duyarlı değilmiş

3-Döngü ve `apply()` fonksiyonları ile sütun sütun istatistik çıkarabildik, R gerçekten RAKS EDİYOR.

4-Veri setlerinin nasıl anlamdırılacağı sonucuna vardıldı.

5-Sonuç olarak bu proje ile hem R 'a hemde analitik düşünceye dahada yakınlaştık.
