project:
  type: website

website:
  title: "Yakit Tüketim Veri İncelemesi"
  navbar:
    left:
      - href: index.qmd
        text: Ana Sayfa
      - href: about.qmd
        text: Hakkında
      - href: project.qmd
        text: Proje

format:
  html:
    theme: cosmo
    toc: true
